image: node:6
clone:
  depth: full
pipelines:
  branches:
    development:
      - step:
          script:
            - npm install
            - git push https://heroku:2e34b2f6-457a-4272-93be-2494720a5804@git.heroku.com/lottery-demo.git HEAD
    master:
      - step:
          script:
            - npm install
            - git push https://heroku:2e34b2f6-457a-4272-93be-2494720a5804@git.heroku.com/lottery-demo.git HEAD
